### PR TITLE
Extract member page class

### PR DESCRIPTION
**Pull request by ondenman**
The scraper is currently broken (see: https://github.com/everypolitician-scrapers/albania-kuvendi/issues/14, https://github.com/everypolitician/everypolitician-data/issues/25382 and https://github.com/everypolitician/everypolitician-data/issues/25290 and https://github.com/everypolitician/everypolitician-data/issues/25382). This is a step towards making changes to the scraper so that it captures data for all members correctly.

The next step will be to fix the `invalid byte sequence` error (https://github.com/everypolitician/everypolitician-data/issues/25382)

### CODE REVIEW

**Review by tmtmtmtm — COMMENTED** [review]
I'm very reluctant to check in tests that are deliberately broken. What's your thinking for that?

**Comment by ondenman** [comment]
I added it to show that it was the expected behaviour. @tmtmtmtm Should I reset to a previous commit?

**Comment by tmtmtmtm** [comment]
I'm not sure what you mean by "expected behaviour" — you mean that it's known to be broken, or that that's what it actually _should_ do? If it's the former then, no, I don't believe it should be checked in as
 a broken version. You should simply add the fix for it as a regression test (which will then fail against `master`) when fixing it. Alternatively, if you want to record now something that's know to be broken, you can add a `skip` test (though that would need to be a full-blown test of its own — not something you can do within `scraper_test`).

**Comment by ondenman** [comment]
I've removed the test and have opened an issue (#14) about the class capturing the data incorrectly.

**Comment by ondenman** [comment]
Fixing birth place in: https://github.com/everypolitician-scrapers/albania-kuvendi/pull/15 but `ensure-regression-tests` is currently failing with 

```
The command "bundle exec rake" exited with 0.
0.14s$ bash <(curl -fsSL https://github.com/everypolitician/ensure-regression-tests/raw/v0.1.0/ensure-regression-tests)
error: pathspec 'extract-member-page-class' did not match any file(s) known to git
```

**Pull request merged**
